---
kind: PersistentVolume
apiVersion: v1

metadata:
  name: pv-1
  labels:
    type: local

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path:  /tmp/local-pv1
